DROP TABLE IF EXISTS END_YEAR;
CREATE TABLE "END_YEAR"
(
    "YEAR"     VARCHAR(4) NOT NULL,
    "INS_USER" VARCHAR(50),
    "INS_DATE" DATE,
    "INS_IP"   VARCHAR(15),
    PRIMARY KEY ("YEAR")
);

DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE "USERS"
(
    "ID"          VARCHAR(50)             NOT NULL,
    "NAME"        VARCHAR(50)  DEFAULT '' NOT NULL,
    "PASSWORD"    VARCHAR(200) DEFAULT '' NOT NULL,
    "POSITION"    VARCHAR(50), -- 직급
    "POSITION_GB" VARCHAR(1),  -- 직책구분(0: CEO / 1: Officer / 2: Manager)
    "INS_USER"    VARCHAR(50),
    "INS_DATE"    DATE          DEFAULT NOW(),
    "INS_IP"      VARCHAR(15),
    "MOD_USER"    VARCHAR(50),
    "MOD_DATE"    DATE,
    "MOD_IP"      VARCHAR(15),
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS ORGANIZATION CASCADE;
CREATE TABLE "ORGANIZATION"
(
    "ID"       BIGINT AUTO_INCREMENT PRIMARY KEY,
    "TITLE"    VARCHAR(50) NOT NULL,
    "INS_USER" VARCHAR(10),
    "INS_DATE" DATE,
    "INS_IP"   VARCHAR(15),
    "MOD_USER" VARCHAR(50),
    "MOD_DATE" DATE,
    "MOD_IP"   VARCHAR(15),
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS TASK CASCADE;
CREATE TABLE "TASK"
(
    "ID"            BIGINT AUTO_INCREMENT PRIMARY KEY,
    "YEAR"          VARCHAR(4) NOT NULL,
    "PROJECT_TITLE" VARCHAR(100),
    "TASK_TITLE"    VARCHAR(300),
    "TASK_STATE"    VARCHAR(10),
    "TASK_PROGRESS" VARCHAR(10),
    "INS_USER"      VARCHAR(50),
    "INS_DATE"      DATE DEFAULT NOW(),
    "INS_IP"        VARCHAR(15),
    PRIMARY KEY ("ID")
);

DROP TABLE IF EXISTS TASK_ORGANIZATION_MAPPING CASCADE;
CREATE TABLE "TASK_ORGANIZATION_MAPPING"
(
    "ID"             BIGINT AUTO_INCREMENT PRIMARY KEY,
    "CHARGE_TEAM_ID" BIGINT NOT NULL,
    "TASK_ID"        BIGINT NOT NULL,
    "INS_USER"       VARCHAR(10),
    "INS_DATE"       DATE,
    "INS_IP"         VARCHAR(15),
    "MOD_USER"       VARCHAR(50),
    "MOD_DATE"       DATE,
    "MOD_IP"         VARCHAR(15),
    PRIMARY KEY ("ID"),
    FOREIGN KEY ("CHARGE_TEAM_ID") REFERENCES ORGANIZATION ("ID"),
    FOREIGN KEY ("TASK_ID") REFERENCES TASK ("ID")
);

DROP TABLE IF EXISTS OFFICER_EVALUATION_PERIOD CASCADE;
CREATE TABLE "OFFICER_EVALUATION_PERIOD"
(
    "ID"         BIGINT AUTO_INCREMENT PRIMARY KEY,
    "START_DATE" DATE NOT NULL,
    "END_DATE"   DATE NOT NULL,
    "INS_USER"   VARCHAR(50),
    "INS_DATE"   DATE DEFAULT NOW(),
    "INS_IP"     VARCHAR(15),
    PRIMARY KEY ("ID")
);


DROP TABLE IF EXISTS ORGANIZATION_HIERARCHY CASCADE;
CREATE TABLE "ORGANIZATION_HIERARCHY"
(
    "ID"                         BIGINT AUTO_INCREMENT PRIMARY KEY,
    "ANCESTOR_ORGANIZATION_ID"   BIGINT NOT NULL,
    "DESCENDANT_ORGANIZATION_ID" BIGINT NOT NULL,
    "DEPTH"                      NUMBER NOT NULL,
    "SORT"                       NUMBER,
    PRIMARY KEY ("ID"),
    FOREIGN KEY ("ANCESTOR_ORGANIZATION_ID") REFERENCES ORGANIZATION ("ID"),
    FOREIGN KEY ("DESCENDANT_ORGANIZATION_ID") REFERENCES ORGANIZATION ("ID")
);

DROP TABLE IF EXISTS TASK_EVALUATION CASCADE;
CREATE TABLE "TASK_EVALUATION"
(
    "CHARGE_TEAM_ID" BIGINT                  NOT NULL,
    "TASK_ID"        BIGINT                  NOT NULL,
    "WEIGHT"         NUMBER(10, 2),
    "OFFICER_POINT"  NUMBER(10, 2),
    "CEO_POINT"      NUMBER(10, 2),
    "TASK_GB"         VARCHAR(10),
    "LEVEL_OFFICER"  VARCHAR(10),
    "LEVEL_CEO"      VARCHAR(10),
    "COND_OFFICER"   VARCHAR(10),
    "COND_CEO"       VARCHAR(10),
    "TOTAL_POINT"    NUMBER(10, 2),
    "NOTE"           VARCHAR(500),
    "STATE"          VARCHAR(1) DEFAULT 'N' NOT NULL,
    "INS_USER"       VARCHAR(50),
    "INS_DATE"       DATE        DEFAULT NOW(),
    "INS_IP"         VARCHAR(15),
    "MOD_USER"       VARCHAR(50),
    "MOD_DATE"       DATE,
    "MOD_IP"         VARCHAR(15),
    PRIMARY KEY ("TASK_ID", "CHARGE_TEAM_ID"),
    FOREIGN KEY ("TASK_ID") REFERENCES TASK ("ID"),
    FOREIGN KEY ("CHARGE_TEAM_ID") REFERENCES ORGANIZATION ("ID")
);

DROP TABLE IF EXISTS EVALUATION_TOTAL CASCADE;
CREATE TABLE "EVALUATION_TOTAL"
(
    "ID"          BIGINT AUTO_INCREMENT PRIMARY KEY,
    "TEAM_ID"     BIGINT      NOT NULL,
    "YEAR"        VARCHAR(4) NOT NULL,
    "TOTAL_POINT" NUMBER(10, 2),
    "RANKING"     VARCHAR(1),
    "TEAM_TITLE"  VARCHAR(50),
    "NOTE"        VARCHAR(500),
    "INS_USER"    VARCHAR(50),
    "INS_DATE"    DATE DEFAULT NOW(),
    "INS_IP"      VARCHAR(15),
    "MOD_USER"    VARCHAR(50),
    "MOD_DATE"    DATE,
    "MOD_IP"      VARCHAR(15),
    PRIMARY KEY ("ID"),
    FOREIGN KEY ("TEAM_ID") REFERENCES ORGANIZATION ("ID")
);

DROP TABLE IF EXISTS ORGANIZATION_LEAD CASCADE;
CREATE TABLE "ORGANIZATION_LEAD"
(
    "ID"              BIGINT AUTO_INCREMENT PRIMARY KEY,
    "ORGANIZATION_ID" BIGINT             NOT NULL,
    "LEAD_ID"         VARCHAR(50)       NOT NULL,
    "START_DATE"      DATE DEFAULT NOW() NOT NULL,
    "END_DATE"        DATE, -- 조직 변경될 경우 업데이트
    PRIMARY KEY ("ID"),
    FOREIGN KEY ("ORGANIZATION_ID") REFERENCES ORGANIZATION ("ID"),
    FOREIGN KEY ("LEAD_ID") REFERENCES USERS ("ID")
)